const { join } = require('path')

module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', '-apple-system', 'system-ui', 'Roboto', 'Helvetica Neue', 'sans-serif'],
      },
      colors: {
        primary: '#ff385c',
        'primary-active': '#e00b41',
        'primary-disabled': '#ffd1da',
        error: '#c13515',
        ink: '#222222',
        body: '#3f3f3f',
        muted: '#6a6a6a',
        'muted-soft': '#929292',
        canvas: '#ffffff',
        'surface-soft': '#f7f7f7',
        'surface-strong': '#f2f2f2',
        hairline: '#dddddd',
        'hairline-soft': '#ebebeb',
        'border-strong': '#c1c1c1',
        white: '#ffffff',
        scrim: 'rgba(0,0,0,0.5)',
        'legal-link': '#428bff',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        base: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '64px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '8px',
        md: '14px',
        lg: '20px',
        xl: '32px',
        full: '9999px',
      },
      fontSize: {
        'display-xl': ['700', '28px/line-height'],
        'display-lg': ['500', '22px/line-height'],
        'display-md': ['700', '21px/line-height'],
        'display-sm': ['600', '20px/line-height'],
        'title-md': ['600', '16px/line-height'],
        'title-sm': ['500', '16px/line-height'],
        'body-md': ['400', '16px/line-height'],
        'body-sm': ['400', '14px/line-height'],
        'caption': ['500', '14px/line-height'],
        'caption-sm': ['400', '13px/line-height'],
        'badge': ['600', '11px/line-height'],
        'micro': ['700', '12px/line-height'],
        'tag': ['700', '8px/line-height'],
        'button-md': ['500', '16px/line-height'],
        'button-sm': ['500', '14px/line-height'],
        'nav': ['600', '16px/line-height'],
        'link': ['400', '14px/line-height'],
        'rating': ['700', '64px/line-height'],
      },
      shadow: {
        card: 'rgba(0,0,0,0.02) 0 0 0 1px, rgba(0,0,0,0.04) 0 2px 6px 0, rgba(0,0,0,0.10) 0 4px 8px 0',
      },
    },
  },
  plugins: [],
}